In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
file_path= "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DA0101EN-Coursera/laptop_pricing_dataset_mod1.csv"

In [5]:
filepath = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DA0101EN-Coursera/laptop_pricing_dataset_mod1.csv"
df = pd.read_csv(filepath, header=None)

In [6]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 239 entries, 0 to 238
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       238 non-null    float64
 1   1       239 non-null    object
 2   2       239 non-null    object
 3   3       239 non-null    object
 4   4       239 non-null    object
 5   5       239 non-null    object
 6   6       239 non-null    object
 7   7       235 non-null    object
 8   8       239 non-null    object
 9   9       239 non-null    object
 10  10      239 non-null    object
 11  11      234 non-null    object
 12  12      239 non-null    object
dtypes: float64(1), object(12)
memory usage: 24.4+ KB
None

In [7]:
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,NaN,Manufacturer,Category,Screen,GPU,OS,CPU_core,Screen_Size_cm,CPU_frequency,RAM_GB,Storage_GB_SSD,Weight_kg,Price
1,0.0,Acer,4,IPS Panel,2,1,5,35.56,1.6,8,256,1.6,978
2,1.0,Dell,3,Full HD,1,1,3,39.624,2.0,4,256,2.2,634
3,2.0,Dell,3,Full HD,1,1,7,39.624,2.7,8,256,2.2,946
4,3.0,Dell,4,IPS Panel,2,1,5,33.782,1.6,8,128,1.22,1244

In [10]:
#Write a code that identifies which columns have missing data.
missing_data = df.isnull()
print(missing_data.head())
for column in missing_data.columns.values.tolist():
    print(column)
    print (missing_data[column].value_counts())
    print("")

      0      1      2      3      4      5      6      7      8      9   \
0   True  False  False  False  False  False  False  False  False  False
1  False  False  False  False  False  False  False  False  False  False
2  False  False  False  False  False  False  False  False  False  False
3  False  False  False  False  False  False  False  False  False  False
4  False  False  False  False  False  False  False  False  False  False

      10     11     12
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False
0
0
False    238
True       1
Name: count, dtype: int64

1
1
False    239
Name: count, dtype: int64

2
2
False    239
Name: count, dtype: int64

3
3
False    239
Name: count, dtype: int64

4
4
False    239
Name: count, dtype: int64

5
5
False    239
Name: count, dtype: int64

6
6
False    239
Name: count, dtype: int64

7
7
False    235
True       4
Name: count, dtype: int64

8
8
False    239
Name: count, dtype: int64

9
9
False    239
Name: count, dtype: int64

10
10
False    239
Name: count, dtype: int64

11
11
False    234
True       5
Name: count, dtype: int64

12
12
False    239
Name: count, dtype: int64